#!/usr/bin/env python3
"""
Sinh file SQL chứa ~1k bản ghi mẫu để import vào DB (devices, sensor_data, weather, crop_season, water_balance, irrigation_config).

Dùng khi:
- Chưa dùng Flyway V6 hoặc muốn tái sinh dữ liệu.
- Chạy: python scripts/seed_sample_data.py [--out data/seed_sample.sql] [--records 1000]

Output: file SQL có thể chạy bằng mysql client hoặc copy vào migration.
"""

import argparse
import random
from datetime import datetime, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "data" / "seed_sample.sql"


def main():
    ap = argparse.ArgumentParser(description="Generate sample DB seed SQL (~1k records)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output SQL file path")
    ap.add_argument("--records", type=int, default=1000, help="Number of sensor_data records")
    args = ap.parse_args()

    random.seed(42)
    args.out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "-- Generated by scripts/seed_sample_data.py",
        f"-- Records: {args.records} sensor_data + 1 device + weather + crop_season + water_balance + irrigation_config",
        "SET @device_id = NULL;",
        "",
        "-- 1. Device",
        "INSERT INTO devices (device_code, device_name, location, status, latitude, longitude, altitude, created_at, updated_at, deleted_at)",
        "VALUES ('SG-001', 'Vườn mẫu Hà Nội', 'Hanoi', 'ONLINE', 21.03, 105.85, 12.0, NOW(), NOW(), NULL);",
        "SET @device_id = LAST_INSERT_ID();",
        "",
        "-- 2. Sensor data (~1k rows, 10 min interval)",
    ]

    base_time = datetime.utcnow() - timedelta(minutes=10 * args.records)
    for i in range(args.records):
        t = base_time + timedelta(minutes=10 * i)
        ts = t.strftime("%Y-%m-%d %H:%M:%S")
        temp = round(22.0 + (i % 24) * 0.3 + random.gauss(0, 1.5), 1)
        hum = round(65.0 + (i % 12) + random.gauss(0, 4), 1)
        sm1 = round(25.0 + i * 0.02 + random.gauss(0, 3), 1)
        sm2 = round(28.0 + i * 0.015 + random.gauss(0, 2.5), 1)
        light = round(5000.0 + (i % 24) * 800 + random.gauss(0, 500), 0)
        rain = 1 if random.random() < 0.05 else 0
        lines.append(
            f"INSERT INTO sensor_data (device_id, soil_moisture, soil_moisture_2, temperature, humidity, light_intensity, rain_detected, timestamp, created_at, updated_at, deleted_at) "
            f"VALUES (@device_id, {sm1}, {sm2}, {temp}, {hum}, {light}, {rain}, '{ts}', NOW(), NOW(), NULL);"
        )

    lines.extend([
        "",
        "-- 3. Weather data (current)",
        "INSERT INTO weather_data (location, temperature, humidity, precipitation, precipitation_probability, wind_speed, uv_index, forecast_time, solar_radiation, sunshine_hours, wind_speed_2m, atmospheric_pressure, created_at, updated_at, deleted_at)",
        "VALUES ('Hanoi', 28.0, 72.0, 0.5, 0.2, 2.0, 8.0, NOW(), 22.0, 6.0, 2.0, 101.3, NOW(), NOW(), NULL);",
        "",
        "-- 4. Daily forecast (3 days)",
        "INSERT INTO daily_weather_forecast (location, forecast_date, temp_min, temp_max, temp_avg, humidity_avg, wind_speed_avg, total_rain, precip_prob_avg, avg_clouds, created_at, updated_at, deleted_at)",
        "VALUES ('Hanoi', CURDATE(), 24.0, 32.0, 28.0, 70.0, 2.0, 0.0, 0.2, 40.0, NOW(), NOW(), NULL),",
        "       ('Hanoi', CURDATE() + INTERVAL 1 DAY, 25.0, 33.0, 29.0, 68.0, 2.2, 2.0, 0.3, 50.0, NOW(), NOW(), NULL),",
        "       ('Hanoi', CURDATE() + INTERVAL 2 DAY, 24.0, 31.0, 27.5, 72.0, 1.8, 5.0, 0.4, 60.0, NOW(), NOW(), NULL);",
        "",
        "-- 5. Crop season (Lúa + Đất thịt)",
        "INSERT INTO crop_season (device_id, crop_id, soil_id, start_date, initial_root_depth, status, created_at, updated_at, deleted_at)",
        "SELECT @device_id, (SELECT id FROM crop_library WHERE name LIKE '%Lúa%' LIMIT 1), (SELECT id FROM soil_library WHERE name LIKE '%thịt%' AND name NOT LIKE '%pha%' LIMIT 1), DATE_SUB(CURDATE(), INTERVAL 35 DAY), 0.1, 'ACTIVE', NOW(), NOW(), NULL;",
        "",
        "-- 6. Water balance state",
        "INSERT INTO device_water_balance_state (device_id, shallow_depletion, shallow_taw, shallow_raw, deep_depletion, deep_taw, deep_raw, last_irrigation, soil_moist_history, created_at, updated_at, deleted_at)",
        "VALUES (@device_id, 5.0, 25.0, 12.5, 8.0, 40.0, 20.0, 3.0, '[]', NOW(), NOW(), NULL);",
        "",
        "-- 7. Irrigation config (ai_enabled=1)",
        "INSERT INTO irrigation_config (device_id, soil_moisture_min, soil_moisture_max, soil_moisture_optimal, temp_min, temp_max, light_threshold, irrigation_duration_min, irrigation_duration_max, fuzzy_enabled, auto_mode, ai_enabled, created_at, updated_at, deleted_at)",
        "VALUES (@device_id, 20.0, 60.0, 40.0, 15.0, 35.0, 1000.0, 30, 300, 1, 1, 1, NOW(), NOW(), NULL);",
    ])

    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.records + 1} device + {args.records} sensor_data + weather/crop/water/config to {args.out}")
    print("Run: mysql -u user -p your_db <", args.out)


if __name__ == "__main__":
    main()
